const SELECT_TABLE = "SELECT_TABLE";
const TOGGLE_TABLE = "TOGGLE_TABLE";
const ADD_TABLE_ITEM = "ADD_TABLE_ITEM";
const DELETE_TABLE_ITEM = "DELETE_TABLE_ITEM";
const INCREMENT_MONEY_EARNED = "INCREMENT_MONEY_EARNED";

module.exports = {
  SELECT_TABLE,
  TOGGLE_TABLE,
  ADD_TABLE_ITEM,
  DELETE_TABLE_ITEM,
  INCREMENT_MONEY_EARNED
};
